# Site settings
title: "TechByte Haven"
description: "Daily gadget reviews, hands-on tests & tech insights"
author: "YourName"
url: "https://techbytehaven.github.io"
theme: minima
plugins:
  - jekyll-feed

# Enable pagination (optional)
pagination:
  enabled: true
  per_page: 5